---
apiVersion: v1
kind: Namespace
metadata:
  name: ebyte-rancher-manager
---
apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-manager
  namespace: ebyte-rancher-manager
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  enabled: false
  repo: https://charts.loft.sh
  version: v0.30.1
  chart: vcluster
  valuesContent: |-
    serviceCIDR: 10.53.0.0/16
    controlPlane:
      backingStore:
        etcd:
          deploy:
            enabled: true
            statefulSet:
              highAvailability:
                replicas: 3
              persistence:
                volumeClaimTemplates:
                - metadata:
                    name: data
                  spec:
                    accessModes: [ "ReadWriteOnce" ]
                    storageClassName: harvester-longhorn-bronze
                    resources:
                      requests:
                        storage: 16Gi
      statefulSet:
        highAvailability:
          replicas: 3
        persistence:
          volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: harvester-longhorn-bronze
              resources:
                requests:
                  storage: 16Gi
      distro:
        k8s:
          image:
            registry: ghcr.io
            repository: loft-sh/kubernetes
            tag: v1.33.6
          enabled: true
          imagePullPolicy: IfNotPresent
    sync:
      fromHost:
        secrets:
          enabled: true
          mappings:
            byName:
              "ebyte-rancher-manager/rancher-tls": "cattle-system/rancher-tls"
      toHost:
        ingresses:
          enabled: true
    experimental:
      deploy:
        host:
          manifests: |-
            ---
            apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: rancher-tls
              namespace: ebyte-rancher-manager
            spec:
              commonName: rancher.harvester.dued.eleasar.ch
              dnsNames:
                - rancher.harvester.dued.eleasar.ch
              issuerRef:
                kind: ClusterIssuer
                name: cloudflare-clusterissuer
              secretName: rancher-tls
        vcluster:
          manifests: |-
            ---
            apiVersion: v1
            kind: Namespace
            metadata:
              name: cattle-system
          helm:
            - chart:
                name: rancher
                repo: https://releases.rancher.com/server-charts/stable
                version: 2.13.0
              release:
                name: rancher
                namespace: cattle-system
              values: |-
                agentTLSMode: system-store
                hostname: rancher.harvester.dued.eleasar.ch
                replicas: 3
                bootstrapPassword: P@ssword123A
                ingress:
                  tls:
                    secretName: rancher-tls
                    source: secret
